// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: delete_user_reading.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const deleteUserReading = `-- name: DeleteUserReading :exec
DELETE FROM user_reading
WHERE user_id = $1 AND book_id = $2
`

type DeleteUserReadingParams struct {
	UserID uuid.UUID
	BookID uuid.UUID
}

func (q *Queries) DeleteUserReading(ctx context.Context, arg DeleteUserReadingParams) error {
	_, err := q.db.ExecContext(ctx, deleteUserReading, arg.UserID, arg.BookID)
	return err
}
