// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: update_user_reading.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const updateUserReading = `-- name: UpdateUserReading :one
UPDATE user_reading SET status = $3
WHERE user_id = $1 AND book_id = $2
RETURNING 1
`

type UpdateUserReadingParams struct {
	UserID uuid.UUID
	BookID uuid.UUID
	Status ReadingStatus
}

func (q *Queries) UpdateUserReading(ctx context.Context, arg UpdateUserReadingParams) (int32, error) {
	row := q.db.QueryRowContext(ctx, updateUserReading, arg.UserID, arg.BookID, arg.Status)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}
