// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: get_user_by_id.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const getUserById = `-- name: GetUserById :one
SELECT login_name, email, birth_date FROM users
WHERE id = $1
`

type GetUserByIdRow struct {
	LoginName string
	Email     string
	BirthDate sql.NullTime
}

func (q *Queries) GetUserById(ctx context.Context, id uuid.UUID) (GetUserByIdRow, error) {
	row := q.db.QueryRowContext(ctx, getUserById, id)
	var i GetUserByIdRow
	err := row.Scan(&i.LoginName, &i.Email, &i.BirthDate)
	return i, err
}
