// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: get_user_by_id.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const getUserByID = `-- name: GetUserByID :one
SELECT login_name, email, birth_date FROM users
WHERE id = $1
`

type GetUserByIDRow struct {
	LoginName string
	Email     string
	BirthDate sql.NullTime
}

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (GetUserByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i GetUserByIDRow
	err := row.Scan(&i.LoginName, &i.Email, &i.BirthDate)
	return i, err
}
