// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: update_user.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const updateUser = `-- name: UpdateUser :one
UPDATE users SET login_name = $2, email = $3, birth_date = $4, hashed_password = $5, updated_at = NOW()
WHERE id = $1
RETURNING 1
`

type UpdateUserParams struct {
	ID             uuid.UUID
	LoginName      string
	Email          string
	BirthDate      sql.NullTime
	HashedPassword string
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (int32, error) {
	row := q.db.QueryRowContext(ctx, updateUser,
		arg.ID,
		arg.LoginName,
		arg.Email,
		arg.BirthDate,
		arg.HashedPassword,
	)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}
